# -*- coding: utf-8 -*-
"""Bangun_datar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5Yd2WxgbA_2ujwo8YtFB5hcLISYiV1m
"""

from abc import ABC, abstractmethod
import math

class BangunDatar(ABC):
    def __init__(self, nama):
        self.nama = nama

    @abstractmethod
    def hitung_luas(self):
        pass

class Persegi(BangunDatar):
    def __init__(self, nama, sisi):
        super().__init__(nama)
        self.sisi = sisi

    def hitung_luas(self):
        return self.sisi ** 2

class Segitiga(BangunDatar):
    def __init__(self, nama, alas, tinggi):
        super().__init__(nama)
        self.alas = alas
        self.tinggi = tinggi

    def hitung_luas(self):
        return 0.5 * self.alas * self.tinggi

class Lingkaran(BangunDatar):
    def __init__(self, nama, jari_jari):
        super().__init__(nama)
        self.jari_jari = jari_jari

    def hitung_luas(self):
        return math.pi * self.jari_jari ** 2

class PersegiPanjang(BangunDatar):
    def __init__(self, nama, panjang, lebar):
        super().__init__(nama)
        self.panjang = panjang
        self.lebar = lebar

    def hitung_luas(self):
        return self.panjang * self.lebar

class JajarGenjang(BangunDatar):
    def __init__(self, nama, alas, tinggi):
        super().__init__(nama)
        self.alas = alas
        self.tinggi = tinggi

    def hitung_luas(self):
        return self.alas * self.tinggi

